sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: amd4tRpTsh62kDYAzky3QrTV9g5FAub7pBbC42qmZ/ERSfAFY4N4Lm/2glmMHsBC4nS6LPfH7Voz14+viq2MJSefqkSpgxTTgfWSqgCfmgiP1aLo4lA0UWxiYPalPTpgE6O4DIQbNS+6C1GI0B8gooDas7gJj+426yfyI2ocJp+o8K/PiOeMjB72lZ9AqVf6ibkP/1PHf7rxkbJxde7ih3Y/R3h1QGxEoqkQpIFh8dXRLz0gHm+q08MpZzvb99BjDSTLJ9MkBpowvmhRhv3dZVIWOqZPozl2kHlb4NMKSnBmBow+RtpwQhjewHNsrap8CUwVN0mcEB/cJc0rkYeYfw0IJ/GWuLYPSwggsVETzQwEqFsLUFN+5ji4ZEYrCRgJnIDlbAY4396t9fMGnk4HDZq4VOi/DMz3Ei4Z/nfAn1Xg3i0ZvOWO+NgY2kTYlrJjibmOrS8LCkHfP0t05sz1ptyHCxsHFeHc518la6NDo9PKqCDZY/zYWceMNfrWJK9i64Lm/fychA5SwV/Tl47F0210An/7q/nGdVeLbPWAKKD3qWeSGZCyqWPrIV1Ut/GbNqedZA69OsbO/s/T7e+9+cVd/Y4yy6cZWk+nGtXcC/sbAzdu8xdu/031+sblmxHwWRt9wFMVWJ0VU+a37h5UbpMSMRDM7M1XMc+hX6YPKjE=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Les-Cinq-Cents-Millions-De-La-B-gum_4968
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy